apiVersion: v1
kind: ConfigMap
metadata:
  name: dim-api-config
  labels:
    app: dim-api
data:
  PGHOST: placeholder
  PGPORT: placeholder
  PGDATABASE: placeholder
  PGUSER: placeholder
  PGSSLMODE: require
  SENTRY_DSN: placeholder
